import type { InfoEntry } from "./informacjeTypes";

export const DEFAULT_INFO_ENTRIES: InfoEntry[] = [
  {
    id: "info-001",
    title: "Start sezonu 2025 i nowe oznaczenia łowisk",
    summary: "Dodaliśmy oznaczenia mikro-ikon i filtr po typie zbiornika.",
    publishedAt: "2025-11-29",
    author: "Agnieszka",
    category: "ogloszenia",
    highlight: "Nowe oznaczenia",
    content: [
      "Każde łowisko można oznaczyć zestawem mikro-ikon (głębokość, nurt, struktura dna).",
      "Filtry w galerii i mapie pozwalają szukać miejsc po typie zbiornika i dominującym gatunku.",
      "Dodaliśmy podpowiedzi kontekstowe, aby szybciej przejść do relacji użytkowników z danego miejsca.",
    ],
  },
  {
    id: "info-002",
    title: "Planowane prace serwisowe - niedziela 22:00-23:30",
    summary: "Krótka przerwa techniczna na aktualizacje bezpieczeństwa.",
    publishedAt: "2025-11-26",
    author: "Kuba",
    category: "ogloszenia",
    highlight: "Utrzymanie",
    content: [
      "W tym czasie logowanie i publikowanie postów będzie niedostępne.",
      "Aktualizujemy warstwę bezpieczeństwa oraz certyfikaty TLS.",
      "Po wdrożeniu zobaczysz krótszy czas ładowania stron publicznych.",
    ],
  },
  {
    id: "info-003",
    title: "Release 1.4 - szybsza galeria i tryb offline szkiców",
    summary: "Galeria ładuje się ~30% szybciej, szkice zapisują się lokalnie.",
    publishedAt: "2025-11-24",
    author: "Magda",
    category: "aktualnosci",
    highlight: "Wydanie 1.4",
    content: [
      "Nowy loader obrazów wykorzystuje progressive rendering i optymalizację miniatur.",
      "Szkice zapisujemy w przeglądarce, więc przy utracie sieci treść zostaje z Tobą.",
      "Drobne poprawki UI: wyraźniejsze badge gatunków i kontrast w trybie nocnym.",
    ],
  },
  {
    id: "info-004",
    title: "Nowy widget pogody na stronie głównej",
    summary: "Prognoza z presją i fazą księżyca pod Twoje łowiska.",
    publishedAt: "2025-11-20",
    author: "Piotr",
    category: "aktualnosci",
    content: [
      "Dodaliśmy presję, wilgotność i siłę wiatru na osi czasu z mikroanimacją trendów.",
      "Widget wykorzystuje zapisane łowiska, by pokazać trafniejszą prognozę.",
      "Przełącznik wizualizacji: klasyczny wykres liniowy lub kompaktowa lista godzinowa.",
    ],
  },
  {
    id: "info-005",
    title: "Konkurs: Najlepsza relacja z jesiennej wyprawy",
    summary: "Dodaj relację do 15.12, oznacz gatunek i sprzęt. Nagroda 500 zł.",
    publishedAt: "2025-11-18",
    author: "Agnieszka",
    category: "konkursy",
    highlight: "Do 15.12",
    content: [
      "Relacja powinna zawierać minimum 3 zdjęcia i krótki opis techniki.",
      "Liczymy na wskazanie warunków: temperatura, głębokość, przynęta.",
      "Wyniki ogłosimy 18.12 w tej sekcji oraz na Discordzie.",
    ],
  },
  {
    id: "info-006",
    title: "Fotograficzne wyzwanie: \"Złota godzina\"",
    summary: "Zdjęcie 30 min po wschodzie lub przed zachodem. Wyniki 05.12.",
    publishedAt: "2025-11-10",
    author: "Kuba",
    category: "konkursy",
    content: [
      "Do zgłoszenia dodaj lokalizację i krótką historię kadru.",
      "Liczy się kompozycja, światło i kontekst wędkarski.",
      "Najlepsze prace pokażemy w wyróżnionej sekcji galerii.",
    ],
  },
  {
    id: "info-007",
    title: "Spotkanie społeczności w Poznaniu",
    summary: "Sobota 07.12, warsztaty z feedera i demo echosondy DIY.",
    publishedAt: "2025-11-28",
    author: "Piotr",
    category: "wydarzenia",
    content: [
      "Start 10:00, jezioro Rusałka - altana przy północnym pomoście.",
      "Warsztaty: feeder light, czytanie dna, szybkie naprawy sprzętu w terenie.",
      "Rejestracja ograniczona - 40 miejsc, decyduje kolejność zgłoszeń.",
    ],
  },
  {
    id: "info-008",
    title: "Pytania i odpowiedzi na żywo na Discordzie - roadmapa zimowa",
    summary: "Priorytety: push, system rang i klub łowisk.",
    publishedAt: "2025-11-22",
    author: "Magda",
    category: "wydarzenia",
    content: [
      "Odpowiadamy na pytania o powiadomienia i personalizację feedu.",
      "Zbieramy propozycje rang i nagród za aktywność na forum.",
      "Link do kanału ogłosimy 30 minut przed startem w tej sekcji.",
    ],
  },
  {
    id: "info-009",
    title: "Devlog #12 - migracja na nowy cache",
    summary: "Hybrydowy cache (edge + Redis). Mniej missów i szybsze API.",
    publishedAt: "2025-11-25",
    author: "Kuba",
    category: "kulisy",
    highlight: "Devlog",
    content: [
      "Edge cache serwuje statyczne assety, Redis trzyma gorące listy tematów.",
      "Spadek TTFB o 18% w godzinach szczytu według naszych pomiarów.",
      "Automatyczne unieważnianie kluczy przy publikacji nowych wątków.",
    ],
  },
  {
    id: "info-010",
    title: "Refaktoryzacja wyszukiwarki - lepsze dopasowanie gatunków",
    summary:
      "Poprawiony scoring fraz po polsku i transliteracja łacińskich nazw.",
    publishedAt: "2025-11-16",
    author: "Agnieszka",
    category: "kulisy",
    content: [
      "Ranking preferuje frazy gatunków po polsku, obsługuje też łacinę.",
      "Wyniki grupujemy po typie treści: relacje, galerie, dyskusje.",
      "Wkrótce dodamy podpowiedzi kontekstowe pod polem wyszukiwarki.",
    ],
  },
];
